from datetime import datetime

import resend

from config import RESEND_API_KEY, EMAIL_FROM, EMAIL_TO

resend.api_key = RESEND_API_KEY


def _build_html(content: str, date_str: str) -> str:
    return f"""\
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:\
-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <div style="max-width:600px;margin:20px auto;background:#ffffff;\
border-radius:8px;overflow:hidden;border:1px solid #e0e0e0;">
    <div style="background:#24292e;color:#ffffff;padding:20px 24px;">
      <h1 style="margin:0;font-size:22px;">GitHub Trending Daily</h1>
      <p style="margin:4px 0 0;font-size:14px;color:#8b949e;">{date_str}</p>
    </div>
    <div style="padding:20px 24px;color:#24292e;line-height:1.6;font-size:15px;">
      {content}
    </div>
    <div style="padding:16px 24px;background:#f6f8fa;font-size:12px;\
color:#656d76;text-align:center;">
      Generated by GitHub Trends Daily Summary
    </div>
  </div>
</body>
</html>"""


def send_email(summary_html: str) -> dict:
    date_str = datetime.now().strftime("%B %d, %Y")
    full_html = _build_html(summary_html, date_str)

    params: resend.Emails.SendParams = {
        "from": EMAIL_FROM,
        "to": [EMAIL_TO],
        "subject": f"GitHub Trending - {date_str}",
        "html": full_html,
    }
    return resend.Emails.send(params)
